---
name: Bug Report
about: Report a bug to help us improve
title: '[Bug]: '
labels: 'bug'
assignees: ''
---

## Bug Description

A clear and concise description of what the bug is.

## Steps to Reproduce

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected Behavior

What you expected to happen.

## Actual Behavior

What actually happened instead.

## Screenshots

If applicable, add screenshots to help explain your problem.

## Environment

Include details about your environment:

- OS: [e.g., macOS 14, Ubuntu 22.04]
- Version: [e.g., v1.2.3]
- Language/Runtime version: [e.g., Python 3.11, Node.js 20]

## Additional Context

Add any other context about the problem here.
